# Generated by Django 4.2.4 on 2023-08-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personality_test", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="admin_only",
            field=models.BooleanField(default=False),
        ),
    ]
